project_id = "hooxnftxqfwhxnapobfx"

[auth.email]
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Verify your Vroomever account"
content_path = "./supabase/templates/confirmation.html"
